name: flutter_barcode_scanner_plugin
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 0.0.1
homepage: https://github.com/jhonathanqz/flutter_barcode_scanner_plugin

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.qztech.flutter_barcode_scanner_plugin
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: FlutterBarcodeScannerPlugin
